version: '1.0'
services:
  web:
      build: .

      ports:
         - "5173:5173"

      volumes:
         - .:/app
         - /app/node-modules
      environment:
         - CHOKIDAR_USEPOLLING=true